"""add assigned_to to orders

Revision ID: bbce038d9a13
Revises: 8124f4d80b72
Create Date: 2026-02-02 15:09:55.313152

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'bbce038d9a13'
down_revision: Union[str, None] = '8124f4d80b72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('assigned_to', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_orders_assigned_to'), 'orders', ['assigned_to'], unique=False)
    op.create_foreign_key(None, 'orders', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_assigned_to'), table_name='orders')
    op.drop_column('orders', 'assigned_to')
    # ### end Alembic commands ###
